---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: flux-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  namespace: flux-system
spec:
  selector:
    app: nginx-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
