apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: flux-system
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379  # Service port
      targetPort: 6379  # Container port
  type: ClusterIP  # Use ClusterIP for internal communication